
name: test-bench

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
      - run: poetry install

      - name: Test with pytest
        run: poetry run pytest --cov
